### ISSUE TITLE
Errore in riepilogo minimi di vendita

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#10]
Nel riepilogo minimi di vendita non esce il prezzo di listino della macchina

![riepilogo minimi di vendita](https://user-images.githubusercontent.com/43198045/45634221-18e61400-baa2-11e8-80fd-180f77c941af.JPG)

**Comment by massicattaneo** [comment]
erano scritti male nel db.xslx - non erano numeri ma caratteri contenenti il simbole dell'euro e del punto. (12.000 -> sbagliato || 12000 -> corretto)
