### ISSUE TITLE
Attrezzature aggiuntive

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#11]
Nel configuratore non riesco a selezionare le attrezzature aggiuntive, inserite da ESPLORA

![attrezzature aggiuntive](https://user-images.githubusercontent.com/43198045/45635602-b858d600-baa5-11e8-9c70-276acf5aac55.JPG)

**Comment by massicattaneo** [comment]
lo sistemo
