### ISSUE TITLE
Leasing

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#12]
Ciao Massi,

nell'anteprima leasing appare sempre n. mesi, invece sopra deve comparire n. mesi e sotto n. rate.

Non esce il valore dell'importo della singola rata, totale rata e totale canoni (se il tasso è diverso da 0).

![leasing](https://user-images.githubusercontent.com/43198045/45670999-9bafb300-bb24-11e8-9234-8a9652dece28.JPG)

**Comment by massicattaneo** [comment]
prova adesso
