### ISSUE TITLE
Cambio sconto in profitto per concessionari

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#14]
TI CHIEDO DI DARE LA PRIORITA' A QUESTA MODIFICA

I concessionari dovranno inserire la percentuale del PROFITTO calcolata sul PREZZO CONCESSIONARIO e non la percentuale di SCONTO.

Esempio:
PROFITTO (inserito dalla direzione del concessionario): 12 %
PREZZO CONCESSIONARIO (ricavato dalla colonna del database): 50.000 €
MINIMO DI VENDITA (concessionario): 56.000 €

Il PREZZO DI LISTINO non viene conteggiato per raggiungere il minimo di vendita.

**Comment by massicattaneo** [comment]
fatto
