### ISSUE TITLE
N. offerte

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#16]
Non riesco a salvare più di 4 offerte.
Se salvo un'ulteriore offerta oltre alle 4 offerte salvate, l'ultima configurata va a sostituire una di quelle 4.

Un venditore mi ha segnalato che arriva massimo a 3.

Uno dovrebbe salvare quante offerte vuole, giusto?

![n offerte](https://user-images.githubusercontent.com/43198045/45736275-bfd5c780-bbea-11e8-8fa3-5832df91d210.JPG)

**Comment by massicattaneo** [comment]
Io riesco a salvarne quante ne voglio.. dammi la tua password che guardo cosa sta succedendo al uo utente

**Comment by massicattaneo** [comment]
Penso che sia un problema di sessione. provare a uscire dall'utenza e rientrare.
