### ISSUE TITLE
Invio depliants attrezzature

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#17]
Ciao Massi, ho inserito i depliants delle attrezzature Simex ma non li invia insieme all'offerta.

**Comment by massicattaneo** [comment]
Bisogna riavviare l'applicazione

**Comment by Samuele84** [comment]
Ciao Massi, ho riprovato a resettare l'applicazione e riavviare di nuovo il configuratore ma i depliant delle attrezzature non li ricevo via mail.

**Comment by massicattaneo** [comment]
Io ho provato con l'attrezzatura: 4813666A  - Lama da neve angolabile CAT e funziona. COn quale non ti funziona?

**Comment by Samuele84** [comment]
Ho riprovato ora e funziona, ma non ho fatto nulla...
Meglio cosi

Ciao
