### ISSUE TITLE
Invio mail d'offerta

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#20]
Ciao Massi,

a volte ci sono dei problemi nell'invio dell'offerta. La pagina continua a caricare ma non invia la mail.
E' successo anche al collega gianmarco.micheletti@cgtedilizia.it (sia con edge che con chrome)

**Comment by massicattaneo** [comment]
Per controllare dovreste dirmi quale preventivo così lo guardo.

**Comment by massicattaneo** [comment]
Ho guardato ed il problema e' nel listino (db.xslx) ... ci sono dei depliants con la posizione non corretta... esempi:
/Depliants/Attrezzature/Benne/BenneCAT_IT.pdf
/Depliants/Attrezzature/Benne/BenneGrapple_IT.pdf

Se l'applicazione non trova i file non puo' inviare la mail ...

**Comment by Samuele84** [comment]
Oh porca bestia, hai ragione...

Non è possibile inserire un'opzione che se il percorso è sbagliato non invia il depliant di quella attrezzatura ma invia comunque la mail?

**Comment by massicattaneo** [comment]
Si é possibile. Però poi come fai a sapere se ci sono errori?

**Comment by Samuele84** [comment]
Se è possibile puoi mandarmi una mail in automatico con l'attrezzatura che da l'errore?
Se è complesso preferisco che non invia quel depliant e siano i venditori a segnalarmi la mancanza

**Comment by massicattaneo** [comment]
ok ti invia la mail in caso di errore
