### ISSUE TITLE
Cambio foto macchine - aggiungere meccanismo anti-cache

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#21]
Ciao Max, vorrei cambiare la foto di una macchina che appare nel configuratore.
Se non ricordo male mi avevi detto che il sistema prende in automatico la prima foto del modello presente nel file db (vedi foto sotto). Tuttavia l'immagine nel configuratore alla sezione modelli non si aggiorna.

![foto 308](https://user-images.githubusercontent.com/43198045/46218322-92a0bc00-c344-11e8-861a-a72c36fa3f8d.JPG)

**Comment by massicattaneo** [comment]
Si viene presa la prima .... ricordati che devi riavviare l'applicazione qui:
https://admin.evennode.com/login?continue=http%3A%2F%2Fadmin.evennode.com%2Fa%2Flist

click al bottone RESTART

**Comment by Samuele84** [comment]
Ciao Massi, in questo modo aggiorna la foto sull'offerta, ma non il modello che compare nel configuratore.

![foto 308](https://user-images.githubusercontent.com/43198045/46282373-9feebe00-c571-11e8-8dda-1c1dbbcf41ef.JPG)

**Comment by massicattaneo** [comment]
Puoi spiegarti meglio che non riesco a capire ...
Tu hai cambiato l'immagine nel listino delle macchine giusto?
dove si vede il cambio e dove no?

**Comment by Samuele84** [comment]
Esatto ho cambiato le immagini nel listino, e correttamente me le aggiorna nel pdf dell'offerta di ogni singola macchina. Tuttavia l'immagine del modello presente nel configuratore alla sezione CONFIGURA IL TUO CATERPILLAR, rimane la stessa. Vedi foto sopra.

**Comment by massicattaneo** [comment]
Io ho provato sul cell e sul portatile e in tutti e due vedeo la nuova foto sia in CONFIGURA che nel PDF. penso possa essere un problema di cache. Appena ho tempo implemento un meccanismo anti-cache.
