### ISSUE TITLE
Prospetto leasing

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#22]
Ciao Max, attualmente nel prospetto leasing per fare i decimali bisogna premere il punto: puoi cambiarlo con la virgola?

![foto](https://user-images.githubusercontent.com/43198045/46594991-7f28ea00-cad6-11e8-9828-3d703a8fdaad.JPG)

**Comment by massicattaneo** [comment]
Tutti i campi con l'euro funzionano cosi .... O cambio tutti o nessuno ... solo questi non ha senso. Cmq in informatica il punto sempre significa la divisione coi decimali. Pero' dimmi tu

**Comment by Samuele84** [comment]
Se il cambio comporta solamente il fatto che per fare i decimali bisogna premere la virgola, la risposta è si. Altrimenti non ho capito...

**Comment by massicattaneo** [comment]
PER IL MOMENTO HO CAMBIATO CHE INSERENDO UNA VIRGOLA SCRIVE IL PUNTO. PER FARE IL CAMBIO CHE FACCIA VEDERE LA VIRGOLA DOVREI LAVORARCI SOPRA UN PO. LO AGGIUNGIAMO COME MODICA FUTURA.
