### ISSUE TITLE
Menditti - concessionario

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#24]
Ciao Massi,

il concessionario Menditti riesce a salvare l'offerta ma quando clicca su anteprima offerta, si apre la nuova pagina web ma non viene visualizzata l'offerta.
Inoltre se clicca invia offerta per mail, continua a caricare la pagina ma non invia la mail.

**Comment by massicattaneo** [comment]
Che macchina e che attrezzature?

**Comment by Samuele84** [comment]
Ciao Massi, ha provato a configurare diverse macchine e per tutte c'è lo stesso problema.
Sono entrato con il suo account dal mio PC e ho gli stessi problemi.
Una sua collega si è registrata e ha gli stessi problemi, secondo me è qualcosa legato all'organizzazione Menditti.
Mi ha lasciato le sue credenziali:
Utente: menditti.ricambi@gmail.com
psw: mario1083

**Comment by massicattaneo** [comment]
Ok. Domenica guardo. Nn scrivere password qui. Cancella il messaggio precedente

**Comment by massicattaneo** [comment]
L'ho forzato e funziona

**Comment by massicattaneo** [comment]
Quando torni sistemo l'eventuale problema di registrazione però adesso funziona

**Comment by Samuele84** [comment]
Grazie Massi!!! Buona vacanza
