### ISSUE TITLE
Invio mail a cliente

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#26]
Ciao Massi, il venditore di CGT Edilizia Gianmarco Micheletti non riesce a inviare le mail di offerta per diverse macchine.
Potresti verificare please?

**Comment by massicattaneo** [comment]
devi dirmi per lo meno quale preventivo. macchina e cliente in modo che lo possa identificare

**Comment by Samuele84** [comment]
Per le seguenti macchine:
Terna 444F2
908M
289D
