### ISSUE TITLE
Calcolo minimi di vendita

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#28]
Ciao Massi,

il concessioanrio Mantella Giovanni ha inserito nella sezione ESPLORA 2 nuove attrezzature denominate:
SISTEMA DI PESATURA PER SKID E TERNE
SISTEMA SATELLITARE

Per la prima gli calcola il profitto impostato (+15%), mentre per la seconda no. Oltre a sistemare il problema descritto, potresti fare in modo che le attrezzature inserite nella sezione ESPLORA vadano inserite con il PREZZO MINIMO DI VENDITA? Spero di essere stato chiaro...

![immagine](https://user-images.githubusercontent.com/43198045/48472181-f4828b80-e7f5-11e8-9fbb-b5a491abfafc.png)

**Comment by massicattaneo** [comment]
Per il problema specifico di mantella l'ho provato e a me funziona ... prova a chiedergli di fare un refresh della pagina e/o login-logout.

**Comment by massicattaneo** [comment]
Per il cambio puoi aprire un altra "issue" specificando bene quelle che vuoi? grazie
