### ISSUE TITLE
Visione Minimi di vendita a CGT

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#29]
Ciao Massi, ti chiedo di far vedere a chi ha il profilo di CGT anche il prezzo MINIMO DI VENDITA (oltre al PREZZO DI LISTINO).

Con il MINIMO DI VENDITA sarà possibile fare il calcolo dell'offerta e l'estrazione del listino

Grazie

**Comment by massicattaneo** [comment]
M devo utilizzare il minimo di vendita o il prezzo CGT? Insomma deve funzionare come un CGT edilizia?

**Comment by Samuele84** [comment]
Il minimo di vendita come CGT Edilizia, solo che CGT non può inviare ordini e vedere le relative offerte speciali

**Comment by massicattaneo** [comment]
Siccome non ho capito ancora ho lasciato che i CGT vedano il prezzo minimo che pero' non e' il prezzo minimo ma il prezzo CGT ... Quello che non ho capito e' se vuoi che vedano il prezzo CGT e il prezzo minimo o solo il prezzo minimo e il prezzo CGT non serve piu' a nulla ... E' facile cambiarlo ma devo capire cosa vuoi... se vuoi chiamami

**Comment by Samuele84** [comment]
Voglio che i CGT vedano:

PREZZO DI LISTINO: si
PREZZO MINIMO DI VENDITA (lo stesso che vedono i venditori di CGT Edilizia): si
PREZZO CONCESSIONARI: no
PREZZO CGT: no

**Comment by massicattaneo** [comment]
ok
