### ISSUE TITLE
Cambio dati ordine per CGTE e concessionari

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#3]
Bisogna cambiare i dati che CGT Edilizia e concessionari devono inserire per effettuare l'ordine.
Sotto trovi i file excel da inviare per mail.

[Dettaglio_ordineMacchina_NOME_VENDITORE_xxxxx.xlsx](https://github.com/massicattaneo/configuratore-cgt-edilizia/files/2378590/Dettaglio_ordineMacchina_NOME_VENDITORE_xxxxx.xlsx)
[Dettaglio_ordineASSCMacchina_NOME_CONCESSIONARIO_xxxxx.xlsx](https://github.com/massicattaneo/configuratore-cgt-edilizia/files/2378591/Dettaglio_ordineASSCMacchina_NOME_CONCESSIONARIO_xxxxx.xlsx)

CAMPI PER VENDITORI CGT EDILIZIA
o	DATA VENDITA
o	DOCUMENTI PERMUTA: PRESENTI/NON PRESENTI/INCOMPLETI
o	VALORE RITIRO PERMUTA: ………………….. € (riporta il valore inserito in fase di configurazione)
o	VALORE ACQUISTO PERMUTA: ………………….. € (riporta il valore inserito in fase di configurazione)
o	DICHIARAZIONE PER SOLLEVAMENTO: SI/NO/N.A.
o	TARGATURA: SI/NO
o	CONSEGNA MECCANICO OFFICINA ESTERNA: SI/NO
o	LEASING: SI/NO
o	DATA PREVISTA CONSEGNA MACCHINA
o	PREZZO TOTALE (ESCLUSA LA PERMUTA):
o	NOTE

CONCESSIONARI
o	DATA PREVISTA CONSEGNA MACCHINA
o	CAMPAGNA: campo descrittivo
o	PREZZO TOTALE:
o	TRASPORTO: (in automatico esce: a nostra cura)
o	PAGAMENTO: come concordato
o      LEASING: si/no
o	NOTE

**Comment by Samuele84** [comment]
Mi sono dimenticato di scriverti che gli ordini devono essere numerati automaticamente nel seguente modo:

anno_venditore/concessionario_n. progressiovo
2018_CANTA_1 (singolo venditore CGT EDILIZIA)
2018_705157_1 (concessionario)

I codici dei concessionari li trovi nel file excel in dropbox.

**Comment by massicattaneo** [comment]
Ma significa che la attuale scheda leasing la rimuovo?

**Comment by Samuele84** [comment]
Cosa intendi per scheda leasing?
Bisogna cambiare i dati da compilare per l'invio dell'ordine e quindi il file Excel che arriverà via mail?

**Comment by massicattaneo** [comment]
nella creazione ordine c'e' un scheda con titolo "leasing" dove se selezioni si vengono mostrate una serie di campi da compilare. Va rimossa? quello che fa fede e' il leasing messo in preventivazione?

**Comment by Samuele84** [comment]
Si perchè bisognerà inserire solamente se la macchina è ordinata con leasing o senza

**Comment by massicattaneo** [comment]
"2018_CANTA_1 (singolo venditore CGT EDILIZIA)" CANTA da dove lo tiro fuori? :)

**Comment by Samuele84** [comment]
E' il cognome del venditore di CGT Edilizia

**Comment by Samuele84** [comment]
Ciao Max, i seguenti DATI devono essere spostati da PERMUTA a Ordine

DICHIARAZIONE PER SOLLEVAMENTO
TARGATURA
CONSEGNA MECCANICO OFFICINA ESTERNA

![foto](https://user-images.githubusercontent.com/43198045/46594890-f8740d00-cad5-11e8-975d-253c1f6d7d8a.JPG)
