### ISSUE TITLE
Aggiornamento listino

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#33]
Ciao Massi, devo aggiornare il listino attrezzature e ho dei dubbi.

Ci sono 5 codici della Spektra, i quali vanno sostituti con 9 codici. Io non so se qualcuno ha preparato delle offerte con i 5 codici che dovrò sostituire.

Come devo procedere per effettuare l'aggiornamento del listino senza creare problemi alle offerte già effettuate?
Ne avevamo parlato ma sinceramente non ricordo, e ho paura a prendere iniziative...

**Comment by massicattaneo** [comment]
Ho aggiunto del codice che se qualcuno ha fatto dei preventivo con codici univoci non esistenti gli salga il messaggio al preventivo di "LISTINO MODIFICATO" e non possa fare ne ordine ne inviare per email. Puo' solo eliminarlo o modificarlo. Tu procedi sulla via che elimini le attrezzature e quei codici li lasci inutilizzati e ne aggiungi nuovi con codici univoci nuovi
