### ISSUE TITLE
Cambio tipologia offerta per CGTE, CGT e concessionari

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#4]
Ti allego il format delle basi d'offerta corrette

[BaseOfferta_CGT_180913.docx](https://github.com/massicattaneo/configuratore-cgt-edilizia/files/2378607/BaseOfferta_CGT_180913.docx)
[BaseOfferta_CGTE_180913.docx](https://github.com/massicattaneo/configuratore-cgt-edilizia/files/2378608/BaseOfferta_CGTE_180913.docx)
[BaseOfferta_ALTRI_180913.docx](https://github.com/massicattaneo/configuratore-cgt-edilizia/files/2378609/BaseOfferta_ALTRI_180913.docx)

**Comment by massicattaneo** [comment]
Rispetto a quella attuale quali sono i cambi? Ho gia fatto dei cambi che erano legati alla permuta. Sono sufficienti?

**Comment by Samuele84** [comment]
Si questa l'hai già sistemata
