### ISSUE TITLE
ORDINE CONCESSIONARI

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#44]
Ciao Massi, nell'effettuazione degli ordini solo dei concessionari ti chiedo di mostrare i seguenti valori:

PREZZO TOTALE ESCLUSA LA PERMUTA: riportare in automatico il PREZZO CONCESSIONARIO
PREZZO OFFERTO: modificarlo in PREZZO CONCESSIONARIO e riportare in automatico il PREZZO CONCESSIONARIO
PREZZO LISTINO: come adesso

Con il fatto di pubblicare lo stock sul configuratore, molti lo stanno utilizzando e probabilmente andremo incontro a molte richieste...

![cattura](https://user-images.githubusercontent.com/43198045/53011774-7a3f5400-3441-11e9-8db0-f4e4c1031dc5.JPG)

**Comment by massicattaneo** [comment]
Ho dei dubbi ... 
se il 
PREZZO TOTALE ESCLUSA LA PERMUTA = PREZZO CONCESSIONARIO
PREZZO OFFERTO (=> PREZZO CONCESSIONARIO) = PREZZO CONCESSIONARIO

mostro 2 volte il PREZZO CONCESSIONARIO e mai il prezzo che ha offerto nell'offerta ...

**Comment by Samuele84** [comment]
Noi abbiamo un listino di acquisto per i concessionari che è il PREZZO CONCESSIONARIO. Poi c'è il prezzo di listino (senza sconto concessionario) ed è il PREZZO DI LISTINO. Poi c'è il prezzo di acquisto macchina, il quale tiene conto di eventuali ulteriori scontistiche, il quale è il PREZZO OFFERTO.
Esempio:
PREZZO LISTINO: 42.000 €
PREZZO OFFERTO: 27.300 € --> Se possibile ti chiedo di modificare solo per i concessionari con PREZZO CONCESSIONARIO
CAMPAGNA SCONTI ULTERIORE: 1000 €
PREZZO TOTALE: 26.300 €
