### ISSUE TITLE
Attrezzature non a listino

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#45]
Attualmente le attrezzature fuori listino, possono essere cancellate solamente da chi le ha inserite.
Ti chiedo di dare la possibilità a:
- direzione CGT Edilizia di cancellare le attrezzature inserite dai venditori CGT Edilizia
- direzione concessionario di cancellare le attrezzature inserite dai venditori del singolo concessionario

**Comment by massicattaneo** [comment]
IL PRIMO PUNTO E' GIA' POSSIBILE

**Comment by massicattaneo** [comment]
PER IL SECONDO PUNTO VUOI CHE UN DIREZIONALE CONCESSIONARIO POSSA VEDERE ANCHE I PREVENTIVI E ORDINI DEI SUOI COMMERCIALI?

**Comment by Samuele84** [comment]
Come si attua il primo punto?

Non siamo ancora pronti per far visualizzare le offerte dei venditori alla direzione dei concessionari, in un futuro apriremo la visualizzazione.

E' possibile attuare il secondo punto senza dover aprire la visualizzazione delle offerte? Se ti crea problemi, evitiamo di attuare il secondo punto.

**Comment by massicattaneo** [comment]
IL PRIMO PUNTO CERCHI L'ATTREZZATURA, VAI SU MODIFICA E SELEZIONI "ELIMINA".

IL SECONDO PUNTO SAREBBE MEGLIO FARE UNA COSA GENERALE, OSSIA CHE IL DIREZIONALE DI UN CONCESSIONARIO POSSA VEDERE MODIFICARE TUTTO QUELLO DEI SUOI COMMERCIALI.
