### ISSUE TITLE
Analisi vendita

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#46]
Solo per CGT Edilizia:
Inviando l'ordine in ufficio oltre al dettaglio vendita, vorrei venisse inviato anche il file dell'analisi vendita.

**Comment by massicattaneo** [comment]
Vuoi che alleghi il file o posso aggiungere una pagina al file excel esistente aggiungendo l'analaisi di vendita?

**Comment by Samuele84** [comment]
Preferisco venga aggiunto un foglio di lavoro allo stesso file excel

**Comment by Samuele84** [comment]
Ciao Massi, ho visto che hai chiuso la richiesta ma il problema persiste, in quanto non ricevo l'analisi di vendita con l'ordine effettuato.
