### ISSUE TITLE
Cambio profilo CGT

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#47]
Ciao Massi, per CGT si vorrebbe cambiare il profilo come di seguito riportato:

- CONFIGURARE LA MACCHINA senza poter fare l'offerta, arrivando solamente al prezzo minimo di vendita.
Nella configurazione non si dovrà inserire la permuta, il leasing, gli oneri di vendita
- ESTRAZIONE LISTINO con prezzo di listino e minimi di vendita (non prezzo CGT)
- DISPONIBILITA' MACCHINE

Tale modifica ha un costo?

**Comment by massicattaneo** [comment]
Devo farlo?

**Comment by Samuele84** [comment]
Si procedi pure

**Comment by massicattaneo** [comment]
IL prezzo CGT non era gia' utlizzato
