### ISSUE TITLE
AGGIUNGI ONERE

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#48]
Ciao Massi, se aggiungo un onere di valore superiore a 1000 € il configuratore restituisce un errore. Puoi sistemarlo?

![Onere](https://user-images.githubusercontent.com/43198045/54347977-60f88480-4648-11e9-8937-2db22e4806df.jpg)

**Comment by massicattaneo** [comment]
ok lo sistemo
