### ISSUE TITLE
Creazione riassunto disponibilità

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#49]
Ciao Massi, vorrei che dal configuratore si possa estrarre la disponibilità come file riepilogativo (vedi sotto).

Alcune macchine hanno come date di arrivo 9999-9991-9992-9993, quelle le puoi impostare come voce IN ARRIVO alla fine della disponibilità (la colonna più a destra prima del totale).

[Esempio_disponibilità.pdf](https://github.com/massicattaneo/configuratore-cgt-edilizia/files/3111263/Esempio_disponibilita.pdf)

**Comment by massicattaneo** [comment]
Ok. Appena ho tempo te lo faccio

**Comment by massicattaneo** [comment]
Mi manca qualche aggiustamento

**Comment by Samuele84** [comment]
Ok Massi, riusciresti a finirlo entro domani?

**Comment by massicattaneo** [comment]
Prova a guardarlo adesso...dovrebbe essere sistemato
