### ISSUE TITLE
Attrezzature fuori listino

### ISSUE THREAD

**Issue by massicattaneo** [massicattaneo/configuratore-cgt-edilizia#5]
@Samuele84 
gli utenti inseriranno il prezzo di listino ... 
Come calcolo il Prezzo Minimo di vendita? 
1) CGTE
2) CGT
3) CONCESSIONARI (immagino applichero' lo sconto che ha messo il direzionale)

grazie

**Comment by Samuele84** [comment]
CGTE: il minimo di vendita lo prendi dal file excel database "db"

CONCESSIONARI: applicherai lo sconto che imposta la direzione del concessionario

CGT: per ora lascia solamente il prezzo di listino. Devo capire se gestirlo come i concessionari o come CGTE. Ti farò sapere.

Ciauz
