### ISSUE TITLE
Analisi vendita

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#51]
Ciao Massi, ho visto che hai chiuso la richiesta di cui sotto, ma il problema persiste, in quanto non ricevo l'analisi di vendita con l'ordine effettuato.

![Cattura](https://user-images.githubusercontent.com/43198045/57753337-31b7cf80-76ec-11e9-9537-83a44993a457.JPG)

**Comment by massicattaneo** [comment]
prova adesso

**Comment by Samuele84** [comment]
Ciao Massi, il problema persiste

**Comment by Samuele84** [comment]
Ciao Massi, il problema persiste
