### ISSUE TITLE
Errore sul file excel

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#52]
Ciao Massi, quando apro il file excel dell'ordine appare sempre questa scritta sia a me che ai miei colleghi. Puoi sistemarlo?

![Cattura](https://user-images.githubusercontent.com/43198045/57753464-822f2d00-76ec-11e9-8eef-e4fadbd448f3.JPG)

**Comment by massicattaneo** [comment]
prova adesso

**Comment by Samuele84** [comment]
Ciao Massi, il problema c'è ancora
