### ISSUE TITLE
Offerta salvata con listino modificato

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#56]
Ciao Massi, quando viene aggiornato il listino appare la scritta LISTINO MODIFICATO sulle offerte da aggiornare. Tuttavia non si vede più quale tipo di offerta era stata fatta. E' possibile visualizzare comunque l'offerta vecchia e lasciare la scritta LISTINO MODIFICATO?

![Cattura](https://user-images.githubusercontent.com/43198045/61028486-14844200-a3b9-11e9-803e-cb404e0b0f02.JPG)

**Comment by massicattaneo** [comment]
Si potrebbe ma solo con dei cambi ... e dovresti lasciare i listini vecchi ...

**Comment by Samuele84** [comment]
Ti chiedo di poter visionare il pdf dell'offerta effettuata con il vecchio listino.

**Comment by massicattaneo** [comment]
Hey Sam.... Dovresti pensare una cosa per fare le cose fatte bene ... quale e' il criterio per dire che un preventivo e' vecchio? adesso guardo solo se il veicolo non e' piu nel listino ...  pero' potrei controllare la data rispetto al listino e mettere una opzione che dice "rinnova preventivo con nuovo listino".

**Comment by Samuele84** [comment]
Ciao Massi, va bene il criterio attuale
