### ISSUE TITLE
Leasing

### ISSUE THREAD

**Issue by Samuele84** [massicattaneo/configuratore-cgt-edilizia#6]
Nel prospetto Leasing bisogna cambiare N: RATE con N. MESI.

La base del prospetto leasing è quella allegata (manca il n. di mesi a fianco alla società erogatrice).

Nel file in pdf del prospetto leasing non esce il valore di IMPORTO SINGOLA RATA e IMPORTO RATA TOTALE

Se il tasso è diverso da 0, non esce il valore del tasso e nemmeno il valore del TOTALE CANONI.

[BaseLeasing_CGTE_180917.docx](https://github.com/massicattaneo/configuratore-cgt-edilizia/files/2388105/BaseLeasing_CGTE_180917.docx)

**Comment by massicattaneo** [comment]
per provare fai un preventivo nuovo
